security:
    enable_authenticator_manager: true

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        jwt:
            lexik_jwt: 
                class: App\Entity\User

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/api
            stateless: true
            provider: jwt
            jwt: ~
            
    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY   }
        - { path: ^/api/docs, roles: IS_AUTHENTICATED_ANONYMOUSLY   }
        - { path: ^/api/register, roles: IS_AUTHENTICATED_ANONYMOUSLY  }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
